### PR TITLE
Implement data persistence using Microsoft Access

### PR DESCRIPTION
**Pull request by Vishwas-Adiga**
This PR creates operations to persist object data and implements them using MS Access

### CODE REVIEW

**Comment by Vishwas-Adiga** [comment]
Ready for review

**Review by Rea-Mammen — APPROVED** [review]
Looks good to me! 🤓

**Comment by mehsheed** [comment]
> > * Ig only SessionDatabase Interface is added newly, apart from that everything matches with our DCD
> 
> Yeah, I figured we'd need a session DB that's outside of our model which would keep a record of all session events in the app

Yea, makes sense !

**Review by Yodhin05 — APPROVED** [review]
Looks good!!

**Pull request merged**
